### ISSUE TITLE
Java findings

### ISSUE THREAD

**Issue by neutronscott** [confluentinc/common-docker#151]
5.5.x needs to use Java8u231 or later to satisfy vulnerability scans.
https://www.tenable.com/plugins/nessus/130010
I see a cp-base-new has deb9 but cp-zookeeper and cp-kafka aren't based on it

**Comment by andrewegel** [comment]
We have fixed this in the following:
* Ubi8: https://github.com/confluentinc/common-docker/pull/141
* Deb9: https://github.com/confluentinc/common-docker/pull/146

Debain 8 is so old at this point, that its going to trigger way worse findings than just the java version given that debian:jessie is EoL at this point. We recommend using Ubi8 based images for better security posture. The tag there being `5.5.6-2-ubi8`.
