### ISSUE TITLE
QEMU 6.2 released with support for Apple M1 Sillicon - Support for AArch64

### ISSUE THREAD

**Issue by fsan** [confluentinc/common-docker#175]
Recent changes to QEMU were released and it now supports hvf accelerator for running AArch64 guests.
This might solve the problem reported at https://github.com/confluentinc/common-docker/issues/117.

Source:
[QEMU 6.2 Changelog](https://wiki.qemu.org/ChangeLog/6.2)

The way I tested it was by installing QEMU 6.2 through homebrew and changing qemu-system-aarch64 (at `/System/Volumes/Data/Users/$USER/Library/Containers/com.docker.docker/Data/tasks/qemu-system-aarch64`) configuration to point to the new version.

Please, could you help verifying if the new release of QEMU can help at https://github.com/confluentinc/common-docker/issues/117

Thanks for your attention

**Comment by andrewegel** [comment]
And what was your experience running CP with this emulation?

**Comment by fsan** [comment]
I cannot say I took scientific measures of that, but my perception is that it improved considerably. 

Let me share the full context so it makes more sense. Please, bear with me.
My stack uses kafka + zookeeper + schema-registry and elasticsearch and some python application.

Elasticsearch does provide an arm64 image so no worries there.
For now, I've been using`kymeric/cp-kafka` and `kymeric/cp-zookpeer` and I observed absolute no crashes on these images.
I tried building `schema-registry` locally but I faced some problems I could not solve yet.
The amd64 version provided by default at `confluentinc/cp-schema-registry` crashes about 50% of times I run my application test suite. (just for completion, the test suite and the stack works perfectly fine on another mac amd64)

As far as I could see, after I updated docker configuration to use qemu 6.2 schema-registry has not crashed until now but I face other problems such as communications with the other aforementioned tools.
I suppose it might be because `kymeric` images are much older.

**Comment by andrewegel** [comment]
Thanks for the feedback - Given that effort to resolve #117 will be for Confluent to provide natively built docker images (not emulated like we're doing here), I don't think there's anything actionable for confluent to take on this particular issue, and is only here to provide community solutions and work around to #117.

**Comment by fsan** [comment]
Please, could you share what is needed to be done so maybe someone in the open source community may try to tackle it ?

**Comment by andrewegel** [comment]
The action lies on Confluent's side of things - as in theres nothing for the community to help with. We need to update our build infrastructure to support building ARM64 docker images.
