### ISSUE TITLE
replace java 11 by java 17 

### ISSUE THREAD

**Issue by raphaelauv** [confluentinc/common-docker#179]
Kafka 3.1.0 is officially compatible with java 17 , it would be great to update the base of the common image to use the latest LTS java version

**Comment by andrewegel** [comment]
The respective CP releases will continue to ship with their respective version of Java as per:

https://docs.confluent.io/platform/current/installation/versions-interoperability.html#java-sys-req

JDK17 support will come in the form of a new major CP release, which at this time isn't clear or on a roadmap I'm aware of.

**Comment by raphaelauv** [comment]
confluent 7.1.0 is out with kafka 3.1.X support

https://docs.confluent.io/platform/current/installation/versions-interoperability.html

**Comment by frosiere** [comment]
Any roadmap/document about the official support of Java17 in CP?

**Comment by jonaslb** [comment]
Interestingly, the linked versions-interoperability document from Confluent (linked twice above) *recommends* Java 17 over 11 and 8, but the official distributions still use Java 11. I can't find documentation that says java version updates are reserved for major version CP releases. Perhaps that could be rechecked/revisited? I would have thought that the recommended version is the version shipped in official releases. 

You can also look to e.g. Elastic who have done Java version updates in minor versions of their products and seemingly gotten away just fine with it.

**Comment by raphaelauv** [comment]
base image is sill using java11

https://github.com/confluentinc/common-docker/blob/1365ddb2c09fbddd690ca1dcbc6b5594d2ea0b96/base/Dockerfile.ubi8#L100

but documentation say 

`
Java 17 is the recommended version in this version of Confluent Platform. Java 11 and Java 8 are also supported.
`

**Comment by drozd0** [comment]
Any progress on this issue?

**Comment by yeikel** [comment]
Coming here to comment as well that the docs are confusing because according to this matrix : https://docs.confluent.io/platform/current/installation/versions-interoperability.html#java

The recommended version of Java since `7.3.x` is Java 17, but when I pulled the latest version of `confluentinc/cp-kafka-connect` 
(https://hub.docker.com/layers/confluentinc/cp-kafka-connect/7.5.0/images/sha256-5edc8b50cde5d1abf719326f678ba548bb146da5afd39a8522eee319a902290d?context=explore) locally, the Java version it brings with is Java 11

> $ java --version
> openjdk 11.0.20 2023-07-18 LTS
> OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
> OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)
>

**Comment by whgibbo** [comment]
Any update on this ?

**Comment by alwaysbemark** [comment]
Would love an update on this as well, this prevents a lot of teams from moving on from Java 11. Thank you!

**Comment by yeikel** [comment]
I think that to avoid being blocked you can try what I mentioned above and just install it yourself. As @andrewegel pointed out, it is not even in the roadmap yet so it will take months at best

**Comment by raphaelauv** [comment]
done in confluent 7.7.0
