### ISSUE TITLE
Remove confluent/team from codeowners

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/common-docker#200]
Please remove confluent/team from the codeowners file: https://github.com/confluentinc/common-docker/blob/master/.github/CODEOWNERS

there are 763 members of that team who don’t all need to be alerted on every update of every PR

**Comment by lyoung-confluent** [comment]
@chuck-confluent I don't own this repository, it looks like `@confluentinc/team` was added by @andrewegel in #184. My migration scripts explicitly avoided assigning any repositories to `@confluentinc/team`

**Comment by lyoung-confluent** [comment]
Looks like @gracechensd is addressed this in #201
